before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
bundler_args: --without development production --quiet
before_install:
  - export BUNDLE_GEMFILE="`pwd`/Gemfile"
script:
  - bundle exec rake db:reset AUTO_ACCEPT=1 && bundle exec rake spree_sample:load
  - bundle exec rake spec
rvm:
  - 2.1.5
